# Site Settings


# Name of your site (displayed in the header)
myname: Avinash Prabhu
alias: Avinash
# Short bio or description (displayed in the header)
byline: The only problem without a solution is an improperly phrased one.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/Avinash2468


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: Avinash Prabhu
  flickr:
  github: Avinash2468
  instagram:
  linkedin: Avinash Prabhu
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: Avinash Prabhu

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "http://avinash2468.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


title: Avinash Prabhu
email: avinash.prabhu@students.iiit.ac.in
description: >
  Avinash Prabhu's personal blog.

github_username:  Avinash2468
facebook_username: Avinash Prabhu
linkedin_username:  Avinash Prabhu
facebook_id: Avinash Prabhu
linkedin_id: Avinash Prabhu
address: IIIT-Hyderabad, 500032, India
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
